apiVersion: v1
kind: ImageStream
metadata:
  name: jaeger-agent
spec:
  lookupPolicy:
    local: false
  tags:
    - from:
        kind: DockerImage
        name: 'jaegertracing/jaeger-agent:latest'
      name: latest
      referencePolicy:
        type: Source
